### ISSUE TITLE
Please Update get_core() and Noisymask/cleanmask planes

### ISSUE THREAD

**Issue by ReclusiveEagle** [BluBb-mADe/vapoursynth-Hysteria#2]
Hysteria is currently broken past VapourSynth R54 because get_core() has been depreciated.
Beyond the get core issue noisymask and cleanmask both have errors stating that there are too many planes.

Disabling both:
noisymask = core.std.Expr( ...
cleanmask = core.std.Expr( ...

is a temporary fix however the functionality is worse.

**Comment by BluBb-mADe** [comment]
I never would've thought anyone would actually use this thing ever again.

I just set up a fresh vapoursynth r57 environment and the masking works just fine.
There just seems to be an issue if you pass a greyscale plane.
The whole plane's parameter baffles me somewhat tbf as the original hysteria was only supposed to work on luma anyway.

**Comment by ReclusiveEagle** [comment]
Yeah no a lot of decisions made within the past few cycles that have broken literally every script within the last 3 months and invalidated the entire library of VS plugins are also baffling to me too.
